site_name: Siddhi IO Rabbitmq
site_description: Siddhi IO Rabbitmq Extension
repo_name: Siddhi-IO-Rabbitmq
repo_url: https://github.com/siddhi.io/siddhi-io-rabbitmq
edit_uri: https://github.com/siddhi.io/siddhi-io-rabbitmq/blob/master
copyright: Siddhi - Documentation
theme:
  name: material
  logo: images/siddhi-logo.svg
  favicon: images/favicon.ico
  palette:
    primary: teal
    accent: teal
extra_css:
- assets/stylesheets/extra.css
extra_javascript:
- assets/javascripts/extra.js
extra:
  social:
  - type: github
    link: https://github.com/siddhi-io/siddhi
  - type: medium
    link: https://medium.com/siddhi-io
  - type: twitter
    link: https://twitter.com/siddhi_io
  - type: linkedin
    link: https://www.linkedin.com/groups/13553064
google_analytics:
- UA-103065-28
- auto
markdown_extensions:
- markdown.extensions.admonition
pages:
- Information: index.md
- API Docs:
  - latest: api/latest.md
  - 3.0.4: api/3.0.4.md
  - 3.0.3: api/3.0.3.md
  - 3.0.2: api/3.0.2.md
  - 3.0.1: api/3.0.1.md
  - 3.0.0: api/3.0.0.md
  - 2.0.0: api/2.0.0.md
  - 1.1.1: api/1.1.1.md
  - 1.1.0: api/1.1.0.md
  - 1.0.20: api/1.0.20.md
  - 1.0.19: api/1.0.19.md
  - 1.0.18: api/1.0.18.md
  - 1.0.17: api/1.0.17.md
  - 1.0.16: api/1.0.16.md
  - 1.0.15: api/1.0.15.md
  - 1.0.14: api/1.0.14.md
- License: license.md
